In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabulary size
voc_size=10000

In [24]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7277, 6497, 7575, 8016],
 [7277, 6497, 7575, 4668],
 [7277, 7491, 7575, 7006],
 [598, 8111, 8855, 4601, 5232],
 [598, 8111, 8855, 4601, 9772],
 [8053, 7277, 4025, 7575, 1790],
 [1205, 8067, 3176, 4601]]

In [25]:
## word Embedding Representation
 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7277 6497 7575 8016]
 [   0    0    0    0 7277 6497 7575 4668]
 [   0    0    0    0 7277 7491 7575 7006]
 [   0    0    0  598 8111 8855 4601 5232]
 [   0    0    0  598 8111 8855 4601 9772]
 [   0    0    0 8053 7277 4025 7575 1790]
 [   0    0    0    0 1205 8067 3176 4601]]


In [27]:
## feature representation
dim=10
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))

model.compile(optimizer='adam', loss='mse')

In [28]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)
 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[[-1.0924529e-02,  3.3219904e-04, -6.9355145e-03, -2.9551698e-02,
         -1.7652832e-02, -2.4466574e-02, -1.7140351e-02, -3.5565831e-02,
          2.1418702e-02, -2.1480024e-02],
        [-1.0924529e-02,  3.3219904e-04, -6.9355145e-03, -2.9551698e-02,
         -1.7652832e-02, -2.4466574e-02, -1.7140351e-02, -3.5565831e-02,
          2.1418702e-02, -2.1480024e-02],
        [-1.0924529e-02,  3.3219904e-04, -6.9355145e-03, -2.9551698e-02,
         -1.7652832e-02, -2.4466574e-02, -1.7140351e-02, -3.5565831e-02,
          2.1418702e-02, -2.1480024e-02],
        [-1.0924529e-02,  3.3219904e-04, -6.9355145e-03, -2.9551698e-02,
         -1.7652832e-02, -2.4466574e-02, -1.7140351e-02, -3.5565831e-02,
          2.1418702e-02, -2.1480024e-02],
        [ 7.9385936e-06, -4.0622760e-02,  2.1387313e-02, -2.2136664e-02,
          2.3766864e-02,  2.3045469e-02, -3.8794123e-02,  3.0443694e-02,
         -1.6037546e-02,  2.3434643e-02],
        [-4.8796702e-02, -1.3084635e-03,  1.6687144e-02, -1.

In [30]:
#rnn


why rnn?
#“Traditional neural networks don’t remember previous data, so we use RNNs to capture sequential dependencies.”

# what is rnn
it is a neural network designed for sequentional data
# applications
### stock prediction
### Speech & Audio Processing
### - Text Classification
### - Weather Forecasting
